USE Statistics;

CREATE TABLE FoldersInfo(
    Id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Path VARCHAR(255) NOT NULL,
    Size INT NOT NULL,
    TimeDelta INT UNSIGNED NOT NULL, 
    Date DATETIME DEFAULT CURRENT_TIMESTAMP()
);
