USE Statistics;

CREATE TABLE FoldersInfo(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Path VARCHAR(255) NOT NULL,
    Size INT NOT NULL,
    TimeDelta TIME NOT NULL, 
    Date DATETIME DEFAULT CURRENT_TIMESTAMP()
)
